name: npm build, lint, test and publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
      - uses: actions/checkout@v1
      - name: Use Node v12
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache dependencies
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install dependencies
      - run: yarn
      - name: Lint code
      - run: yarn lint
